name: Responsive Check
on: [push, pull_request]
jobs:
  responsive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install puppeteer
      - run: node responsive-check.js
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshot-*.png # Envia os screenshots como artefato