name: Criar branch para novo colaborador

on:
  member:
    types: [added]

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar branch para o novo colaborador
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COLLABORATOR=${{ github.event.member.login }}
          BRANCH_NAME="colaborador-${COLLABORATOR}"
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Notificar o colaborador
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COLLABORATOR=${{ github.event.member.login }}
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d "{\"title\": \"Bem-vindo, $COLLABORATOR!\", \"body\": \"Criamos automaticamente uma branch para você: \`colaborador-$COLLABORATOR\`! 🚀\"}"
